name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      shell: powershell
      run: |
        Set-Location -Path $env:GITHUB_WORKSPACE

    - name: Give execute permissions to run_tests.sh
      run: chmod +x run_tests.sh



    - name: Run Tests
      shell: powershell
      run: |
        Set-Location -Path .\
        .\run_tests.bat
