name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      shell: powershell
      run: |
        Set-Location -Path $env:GITHUB_WORKSPACE

    - name: List files in current directory
      run: Get-ChildItem -Path .\ -Force


    - name: Run Tests
      shell: powershell
      run: |
        Set-Location -Path .\
        .\run_tests.bat
