name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x run_tests.sh

    - name: Run Tests
      run: ./run_tests.sh
