name: Run Tests

on:
  push:
    branches:
      - test1
      - master

jobs:
  test:
    runs-on: windows-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build project
      run: msbuild /p:Configuration=Debug /m /p:Platform=x64
      
    - name: Print current working directory
      run: |
        dir 
      
    - name: Clear test output file
      run: echo. > tests_project\test_output_1.txt

    - name: Print current working directory
      run: |
        dir 
        
    - name: Run Tests
      run: |
        .\run_tests.bat
        
    
