name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x run_tests.sh
        
    - name: Print current working directory
      run: |
        pwd
        ls
        
    - name: Print contents of /x64/Debug directory
      run: |
        cd $GITHUB_WORKSPACE/x64/Debug
        ls

    - name: Run Tests
      run: ./run_tests.sh
