name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use appropriate runner for your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Tests
      shell: powershell
      run: .\run_tests.bat
